services:
  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
  nginx:
    image: nginx:latest
    container_name: "Patience"
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
